version: "3"
services:
  backend_db:
    image: postgres:10-alpine
    restart: always
    container_name: backend_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /srv/spring_rest_api_starter/db/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  springbootapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springbootapp
    ports:
    - "8080:8080"
    volumes:
      - /srv/private_parking_reservation/back/logs:/srv/app/logs
      - /srv/private_parking_reservation/back/keys:/srv/app/keys
      - /srv/private_parking_reservation/back/config:/srv/app/config
      - /srv/private_parking_reservation/back/data:/srv/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - backend_db